### ISSUE TITLE
No all css links are detected

### ISSUE THREAD

**Issue by pyMan** [thgreasi/jquery.scopeLinkTags#1]
Hi, this is a cool plugin, thanks!

Anyway I wonder why the CSS_LINK_SELECTOR is not considering link[rel="stylesheet"] elements, sometimes type="text/css" is being omitted, so I think the CSS_LINK_SELECTOR may be defined as follow

```
var CSS_LINK_SELECTOR = 'link[type="text/css"], link[rel="stylesheet"]';
```

**Comment by thgreasi** [comment]
How about adding `link:not([type])`?? Would that be good enough for your case?

**Comment by thgreasi** [comment]
Although this isn't 100% correct according to [MDN](http://devdocs.io/html/element/link).
How about exposing the selector as an option?

**Comment by pyMan** [comment]
Exposing the selector as an option would be great!

**Comment by thgreasi** [comment]
Added in v0.10.0

**Comment by pyMan** [comment]
Thanks!
